apiVersion: v1
kind: ConfigMap
metadata:
  name: shmocker-dockerfile
  namespace: eir
data:
  Dockerfile: |
    FROM alpine:latest
    RUN echo "Building with shmocker (via BuildKit)!"
    RUN apk add --no-cache python3 py3-pip
    WORKDIR /app
    RUN echo 'print("Hello from shmocker!")' > hello.py
    CMD ["python3", "hello.py"]
---
apiVersion: batch/v1
kind: Job
metadata:
  name: shmocker-build-demo
  namespace: eir
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: buildkit
        image: moby/buildkit:v0.17.0-rootless
        env:
        - name: BUILDKITD_FLAGS
          value: --oci-worker-no-process-sandbox
        command:
        - buildctl-daemonless.sh
        args:
        - build
        - --frontend
        - dockerfile.v0
        - --local
        - context=/workspace
        - --local
        - dockerfile=/workspace
        - --output
        - type=oci,dest=/workspace/image.tar
        resources:
          limits:
            cpu: "4"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        securityContext:
          seccompProfile:
            type: Unconfined
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
        - name: dockerfile
          mountPath: /workspace
        - name: buildkitd
          mountPath: /home/user/.local/share/buildkit
      volumes:
      - name: dockerfile
        configMap:
          name: shmocker-dockerfile
      - name: buildkitd
        emptyDir: {}