apiVersion: v1
kind: Namespace
metadata:
  name: shmocker-demo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shmocker-demo-files
  namespace: shmocker-demo
data:
  Dockerfile: |
    FROM alpine:latest
    RUN echo "Building with shmocker!"
    RUN apk add --no-cache python3
    WORKDIR /app
    COPY hello.py .
    CMD ["python3", "hello.py"]
  hello.py: |
    print("Hello from shmocker!")
    print("This image was built without Docker!")
    print("Using BuildKit in rootless mode on Kubernetes")
  build.sh: |
    #!/bin/sh
    echo "=== Shmocker Demo ==="
    echo "Building image using BuildKit in rootless mode..."
    echo ""
    
    # Run the build
    buildctl-daemonless.sh build \
      --frontend dockerfile.v0 \
      --local context=/workspace \
      --local dockerfile=/workspace \
      --output type=oci,dest=/workspace/image.tar
    
    echo ""
    echo "Build complete! Image saved to image.tar"
    ls -lh /workspace/image.tar
---
apiVersion: v1
kind: Pod
metadata:
  name: shmocker-demo-pod
  namespace: shmocker-demo
spec:
  containers:
  - name: buildkit
    image: moby/buildkit:v0.17.0-rootless
    env:
    - name: BUILDKITD_FLAGS
      value: --oci-worker-no-process-sandbox
    command:
    - /bin/sh
    - -c
    - |
      echo "Starting shmocker demo pod..."
      echo "This pod demonstrates building images without Docker"
      echo ""
      chmod +x /workspace/build.sh
      echo "Ready to build. Run: kubectl exec -n shmocker-demo shmocker-demo-pod -- /workspace/build.sh"
      # Keep pod running
      sleep infinity
    securityContext:
      seccompProfile:
        type: Unconfined
      appArmorProfile:
        type: Unconfined
      runAsUser: 1000
      runAsGroup: 1000
    volumeMounts:
    - name: demo-files
      mountPath: /workspace
    - name: buildkitd
      mountPath: /home/user/.local/share/buildkit
  volumes:
  - name: demo-files
    configMap:
      name: shmocker-demo-files
      defaultMode: 0755
  - name: buildkitd
    emptyDir: {}